yorno/config/routes.rb
Yorno::Application.routes.draw do
  get "response/yes"

  get "response/no"

  get "response/count"

  resources :questions

  devise_for :users

  root :to => 'pages#home'
  
  get 'about' => "pages#about"
  get 'question' => "pages#question"
  get 'ask' => "pages#ask"
  
  match '/answer/:id' => 'questions#answer'
  
  get 'yes/:id' => 'response#yes', :as => :yes
  get 'no/:id' => 'response#no', :as => :no

end

yorno/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :response
  
  attr_accessible :question_ans, :question_text, :user_id
end

yorno/app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :question
  
  attr_accessible :count, :no, :yes
  
  
end

yorno/app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :questions
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

yorno/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @questions = Question.all
  end

  def about
  end
  
  def ask
    
  end
  
  def question
    @questions = Question.all
  end
end

yorno/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    @response = Response.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    
    @question = Question.find(params[:id])
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = current_user.questions.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end
  
  # GET /questions/1/answer
  def answer
     @question = Question.find(params[:id])
   end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    
    @question.user_id = current_user.id
    #Create responses for question
    @response = Response.new(params[:response])
    
    @response.yes = 0
    @response.no = 1
    
    @response.save
    

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

yorno/app/controllers/response_controller.rb
class ResponseController < ApplicationController

  # GET /yes/1
  # GET /yes/1.json

  
  def yes
      @response = Response.find(params[:id])
      
      if (@response.yes == nil)
        @response.yes = 1
      else 
        @response.yes += 1
      end
      
      @response.save

      respond_to do |format|
        format.html { redirect_to question_path, notice: 'You have voted YES yay'  }
        format.json { head :no_content }
      end    
    
    
  end

  def no
    @response = Response.find(params[:id])
    
    if (@response.no == nil)
      @response.no = 1
    else 
      @response.no += 1
    end
    
    @response.save

    respond_to do |format|
      format.html { redirect_to question_path, notice: 'You have voted NO'  }
      format.json { head :no_content }
    end    
    
    
  end

  def count
  end
end

yorno/app/helpers/pages_helper.rb
module PagesHelper
end

yorno/app/helpers/questions_helper.rb
module QuestionsHelper
end

yorno/app/helpers/response_helper.rb
module ResponseHelper
end

yorno/app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<p class="push">A project by <a href="#">@denniscamacho</a>, <a href="#">@jjide</a>, and <a href="#">@lawrence_brown_</a></p>
		

	</div>
</div>

yorno/app/views/layouts/_header.html.erb
<div id="wrap">
	<div class="navbar navbar-fixed-top header" >

			<div class="container" >
				
				<ul class=" nav pull-right">
				<li><%= link_to 'About', about_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
					<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
					<% else %>
					<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>
				</ul>
				<div class="logo pull-left">
				<strong><p><%= link_to 'Yeno', root_path %></p></strong>
				</div>
				

				

				<p class="muted">Simple Yes or No Answers</p>
			</div><!-- end container -->

	</div><!--end of navbar-fixed-top -->

yorno/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yorno</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	
	<%= yield %>
</div> <!-- close body container -->

<div id="push"></div>

</div> <!-- closed the wrap -->

<%= render 'layouts/footer' %>

</body>
</html>

yorno/app/views/pages/_question.html.erb
<h1>All Questions</h1>

<table class="table table-striped">
  <tr>
    <th>Questions</th>
    <!-- <th>Answers</th> -->
    <!-- <th></th> -->
   
  </tr>

<% @questions.each do |question| %>
  
	<tr>
    	<td><%= link_to question.question_text, question_path(question) %></td>
    
   		<!-- <td><%= link_to 'Show', question %></td> 
    	<td><%= link_to 'Edit', edit_question_path(question) %></td>
    	<td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  	</tr>

<% end %>
</table>

yorno/app/views/pages/about.html.erb
<h1>About</h1>
<p><strong>Yeno is Coming Soon!!!</strong></p>
<p> Check back again soon </p>

yorno/app/views/pages/ask.html.erb
<h1>Pages#ask</h1>
<p>Find me in app/views/pages/ask.html.erb</p>

yorno/app/views/pages/home.html.erb
	
<% if user_signed_in? %>
	<% if @questions != nil %>
		<%= render '/questions/index' %>
	<% else %>
		<p>you have no questions - Please add one below</p>
		<%= link_to 'questions/new'%>
	<% end %>
	
			
<% else %>
<div class="lead">
	<h1>Welcome to YERNO</h1>
	<p>Answer some questions or Sign up to ask a question</p>
	<%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary btn-large" %>
</div>
<% if user_signed_in? %>
<%= render '/questions/index' %>
<% else %>
<%= render '/pages/question' %>
<% end %>
<% end %>

yorno/app/views/questions/_form.html.erb
<%= simple_form_for(@question, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question_text, :required => true %>

  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class:"btn btn-primary" %>
  </div>
<% end %>

yorno/app/views/questions/_index.html.erb
<h1>My Questions</h1>

<table class="table table-striped">
  <tr>
    <th>Questions</th>
	<th>Yes</th>
	<th>No</th>
    <th></th>
    <th></th>
   
  </tr>

<% @questions.each do |question| %>
<% if user_signed_in? %>
	<% if question.user_id == current_user.id %>
  	<tr>
    	<td><%= link_to question.question_text, question_path(question) %></td>
    	<td></td>
		<td></td>
   		<!-- <td><%= link_to 'Show', question %></td> -->
    	<td><%= link_to 'Edit', edit_question_path(question) %></td>
    	<td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  	</tr>
	<% end %>

<% end %>
<% end %>
</table>

<br />

<% if user_signed_in? %>
<%= link_to 'Add a New Question', new_question_path, class:"btn btn-primary" %>
<% end %>

yorno/app/views/questions/answer.html.erb
<h1>Answer question</h1>

<p> <%= question_text %> </p>
<%= simple_form_for(@question, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question_ans, :required => true, as: :boolean %>

  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class:"btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back', "#" %>

yorno/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

yorno/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

yorno/app/views/questions/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="jumbotron">
	<p>
  		<b>Question:</b>
  		<%= @question.question_text %>
	</p>
</div><!-- close jumbotron -->

<div class="usericon">
	<p>User Icon</p>
</div>


 <%= simple_form_for(@question, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs yeno">
 
<%= link_to "YES", yes_path(@question), :method => "get", class:"btn btn-success btn-large" %>

<%= link_to "NO", no_path(@question), :method => "get", class:"btn btn-danger btn-large" %>
  </div>



<% end %>
<div class="yeno">
	Yes: <%= @response.yes %>
	No: <%= @response.no %>




<p>
<% if user_signed_in? %>

<%= link_to 'Edit', edit_question_path(@question) %> |

<% end %>

<%= link_to 'Back', root_path %>
</p>

</div>

yorno/app/views/response/count.html.erb
<h1>Response#count</h1>
<p>Find me in app/views/response/count.html.erb</p>

yorno/app/views/response/no.html.erb
<h1>Response#no</h1>
<p>Find me in app/views/response/no.html.erb</p>

yorno/app/views/response/yes.html.erb
<h1>Response#yes</h1>
<p>Find me in app/views/response/yes.html.erb</p>